In [4]:
import numpy as np
a=np.array([6,7,8,9])
a

array([6, 7, 8, 9])

In [5]:
import numpy as np
data=np.array([[[8,
27,13,7,22,
8,23,7,25,11,
30,9,29,20],

[14,26,13,21,6,
20,-13,32,14,23,
8,20,15,27],

[14,20,6,21,6,
25,9,23,10,28,8,29,7,
23],

[10,29,12,25,12,
27,9,26,11,24,13,30,
15,30]],

[[7,32,6,31,12,
28,6,20,14,32,7,28,15,
24],

[10,25,6,23,11,
27,14,31,8,20,15,31,7,
26],

[9,23,7,25,11,
23,7,22,6,31,7,32,13,
30],

[7,32,12,28,14,
26,6,32,14,22,8,27,10,
28]],

[[2,18,5,18,7,19,
6,22,6,18,5,3,22,6],

[4,18,6,18,6,18,
8,21,5,18,5,4,20,4],

[6,22,8,21,4,22,
8,20,2,21,4,8,18,5],

[7,22,2,21,6,22,
6,21,5,19,3,3,19,3]],

[[10,20,7,22,-10,
19,8,21,9,18,7,71,20,
10],

[10,18,10,22,11,
19,9,20,9,18,11,9,20,
10],

[8,18,8,18,10,
19,10,20,11,18,8,12,
18,9],

[9,20,7,21,8,18,
8,19,9,20,12,12,18,7]]])

print(data.ndim)
print(data.shape)

november = data[0]
december = data[1]
january = data[2]
february = data[3]
 
print(november)
print(december)
print(january)
print(february)



3
(4, 4, 14)
[[  8  27  13   7  22   8  23   7  25  11  30   9  29  20]
 [ 14  26  13  21   6  20 -13  32  14  23   8  20  15  27]
 [ 14  20   6  21   6  25   9  23  10  28   8  29   7  23]
 [ 10  29  12  25  12  27   9  26  11  24  13  30  15  30]]
[[ 7 32  6 31 12 28  6 20 14 32  7 28 15 24]
 [10 25  6 23 11 27 14 31  8 20 15 31  7 26]
 [ 9 23  7 25 11 23  7 22  6 31  7 32 13 30]
 [ 7 32 12 28 14 26  6 32 14 22  8 27 10 28]]
[[ 2 18  5 18  7 19  6 22  6 18  5  3 22  6]
 [ 4 18  6 18  6 18  8 21  5 18  5  4 20  4]
 [ 6 22  8 21  4 22  8 20  2 21  4  8 18  5]
 [ 7 22  2 21  6 22  6 21  5 19  3  3 19  3]]
[[ 10  20   7  22 -10  19   8  21   9  18   7  71  20  10]
 [ 10  18  10  22  11  19   9  20   9  18  11   9  20  10]
 [  8  18   8  18  10  19  10  20  11  18   8  12  18   9]
 [  9  20   7  21   8  18   8  19   9  20  12  12  18   7]]


In [6]:
print(data)

[[[  8  27  13   7  22   8  23   7  25  11  30   9  29  20]
  [ 14  26  13  21   6  20 -13  32  14  23   8  20  15  27]
  [ 14  20   6  21   6  25   9  23  10  28   8  29   7  23]
  [ 10  29  12  25  12  27   9  26  11  24  13  30  15  30]]

 [[  7  32   6  31  12  28   6  20  14  32   7  28  15  24]
  [ 10  25   6  23  11  27  14  31   8  20  15  31   7  26]
  [  9  23   7  25  11  23   7  22   6  31   7  32  13  30]
  [  7  32  12  28  14  26   6  32  14  22   8  27  10  28]]

 [[  2  18   5  18   7  19   6  22   6  18   5   3  22   6]
  [  4  18   6  18   6  18   8  21   5  18   5   4  20   4]
  [  6  22   8  21   4  22   8  20   2  21   4   8  18   5]
  [  7  22   2  21   6  22   6  21   5  19   3   3  19   3]]

 [[ 10  20   7  22 -10  19   8  21   9  18   7  71  20  10]
  [ 10  18  10  22  11  19   9  20   9  18  11   9  20  10]
  [  8  18   8  18  10  19  10  20  11  18   8  12  18   9]
  [  9  20   7  21   8  18   8  19   9  20  12  12  18   7]]]


4. Print the temperatures for Tuesday of each month.

In [7]:
tuesday= data[:,:,2:4]
print(tuesday)

[[[13  7]
  [13 21]
  [ 6 21]
  [12 25]]

 [[ 6 31]
  [ 6 23]
  [ 7 25]
  [12 28]]

 [[ 5 18]
  [ 6 18]
  [ 8 21]
  [ 2 21]]

 [[ 7 22]
  [10 22]
  [ 8 18]
  [ 7 21]]]


In [8]:
weekdays=data[1:4:2,:,0:9:2]
print(weekdays)

[[[  7   6  12   6  14]
  [ 10   6  11  14   8]
  [  9   7  11   7   6]
  [  7  12  14   6  14]]

 [[ 10   7 -10   8   9]
  [ 10  10  11   9   9]
  [  8   8  10  10  11]
  [  9   7   8   8   9]]]


In [9]:
nov_min = data[:4,::2]
for i, row in enumerate(nov_min):
    np.where(row<8)[0]
    print(i+1,":")


1 :
2 :
3 :
4 :


In [10]:
temperatures = np.array(data)
threshold = 20
weeks_with_high_temperatures =  temperatures[1:3,:,1::2]
[temperatures[1:3,:,1:2] > threshold]
print(weeks_with_high_temperatures)


[[[32 31 28 20 32 28 24]
  [25 23 27 31 20 31 26]
  [23 25 23 22 31 32 30]
  [32 28 26 32 22 27 28]]

 [[18 18 19 22 18  3  6]
  [18 18 18 21 18  4  4]
  [22 21 22 20 21  8  5]
  [22 21 22 21 19  3  3]]]


In [11]:
.there are several strategies that could be used to handle data points like the one you described ,depending on the specific goals and consraints of the analysis you are conducting.
.ignore the data ponit.
.impute the data point.
.investigate the data point.
.exclude the data point from certain analysis.

SyntaxError: invalid syntax (1619133394.py, line 1)

In [ ]:
temperatures = np.array(data)

winter_months = temperatures[:,:,1::2]  #select the winter months(nov,dec,jan,feb)

average_max_temp = np.mean(winter_months) #compute the average temperature of winter months

print(average_max_temp)




20.892857142857142


In [ ]:
temperatures = np.array(data)
#select the min temp for the month of dec
dec_min_temps = temperatures[1,:,::2]
#compute the weekly average min temp for dec
dec_weekly_avg_min_temps = np.mean(dec_min_temps,axis=1)
print(dec_weekly_avg_min_temps) 

[ 9.57142857 10.14285714  8.57142857 10.14285714]


In [ ]:
temperatures = np.array(data)
#select the temperature data for jan abd dec
dec_jan_temps = temperatures[1:3,:,:]
#flatten the temp data in single
# le dimension
flattened_temp = dec_jan_temps.flatten()
#compute the overall temp for dec and jan
overall_avg_temps = np.mean(flattened_temp)
print(overall_avg_temps)




14.892857142857142


In [ ]:
temperatures = np.array(data)
min_temp = np.min(temperatures[1:3,:,:])
#find the indicies of the min temp in the data
min_temp_indices = np.where(temperatures == min_temp)
#the indices will be a tuple of arrays,one for each dimension of the data
#the first element of the tuple correspond the month the second of the week the third of the day
month_index = min_temp_indices[0][0]
week_index = min_temp_indices[1][0]
day_index = min_temp_indices[2][0]
#calculate the month and week based on the indices
month = "december" if month_index == 0 else "january"
week = week_index + 1
#calculate the day of the week based on the day index
#we cab do this by using an offset from first day of the week
#the first week day of the week is monday,so the day of the week is tbhe day index+1
day_of_week = day_index + 1
print(f"the least temperature experienced in {month} was {min_temp} degree on {day_of_week} of week {week}")

the least temperature experienced in january was 2 degree on 1 of week 1


In [ ]:
temperatures = np.array(data)
max_temp = np.max(temperatures[3,:,:])
#the indicies of the maximmum temp in the data
max_temp_indices = np.where(temperatures == max_temp)
month_index = max_temp_indices[0][0]
week_index = max_temp_indices[1][0]
day_index = max_temp_indices[2][0]
# calculate the month and week based on indices
#we can do this by adding the month index to the month(nov)
# and adding the weekn index to the base week(1)
month = month_index + 11
week = week_index +1
#the first day of the week is monday,so  the day pof the week is the day index+1
day_of_week = day_index =1
print(f"the maximum temperature experienced in february was{max_temp} degrees on{day_of_week} of week{week}")

the maximum temperature experienced in february was71 degrees on1 of week1


In [ ]:
temperatures = np.array(data)
nov_temps = temperatures[0,:,:]
nov_avg_temp  = np.mean(nov_temps)
# the maximum temp for each day in nov
nov_max_temps = np.max(nov_temps,axis=1)
#find the days where the maximum temperature was below the average temp
below_avg_days = np.where(nov_max_temps < nov_avg_temp)[0]
print(f"the days in november where the maximum temperature was below the average temperature were:{below_avg_days + 1}")


the days in november where the maximum temperature was below the average temperature were:[]


In [ ]:
#create an empty list to hold the data for the new array
new_data = []
for month_index , month_data in enumerate(temperatures):
    #loop over the week pf month
    for week_index , week_data in enumerate(month_data):
        #check if we have already processed this week
        if week_index < month_index:
            continue
        elif week_index == 0:
            new_data.append(week_data)
            #if this is not the first week of month ,add it to the previous row of the new data list
        else:
            new_data[-1] = np.concatenate([new_data[-1],week_data])
            new_array = np.array(new_data)
            
    

In [ ]:
dec_temps = temperatures[1,:,:]
dec_weekly_avgs = np.mean(dec_temps, axis=1)
#sort the weekly avgs temp in desc order
sort_indices = np.argsort(- dec_weekly_avgs)
#use the sorted indices to sort the data for dec
sorted_dec_data = dec_temps[sort_indices,:]
print(sorted_dec_data)


[[ 7 32 12 28 14 26  6 32 14 22  8 27 10 28]
 [ 7 32  6 31 12 28  6 20 14 32  7 28 15 24]
 [10 25  6 23 11 27 14 31  8 20 15 31  7 26]
 [ 9 23  7 25 11 23  7 22  6 31  7 32 13 30]]


In [ ]:
temperatures = np.array(data)
avg_temps = np.mean(temperatures[:,:,:3],axis=(1,2))
#sort the average temp in desc order
sorted_indices = np.argsort(-avg_temps)
sorted_data = temperatures[sorted_indices,:,:3]
print(sorted_data)

[[[ 8 27 13]
  [14 26 13]
  [14 20  6]
  [10 29 12]]

 [[ 7 32  6]
  [10 25  6]
  [ 9 23  7]
  [ 7 32 12]]

 [[10 20  7]
  [10 18 10]
  [ 8 18  8]
  [ 9 20  7]]

 [[ 2 18  5]
  [ 4 18  6]
  [ 6 22  8]
  [ 7 22  2]]]


In [ ]:
#calculate the mean and standard dev of the temp data
mean_temp = np.mean(temperatures)
std_temp = np.std(temperatures)
#the indices of the outlier values 
outlier_indexes = np.where(np.abs(temperatures - mean_temp) > 3 * std_temp)
print(outlier_indexes)

(array([0, 3], dtype=int64), array([1, 0], dtype=int64), array([ 6, 11], dtype=int64))


In [12]:
temperatures = np.array(data)
print(temperatures)

[[[  8  27  13   7  22   8  23   7  25  11  30   9  29  20]
  [ 14  26  13  21   6  20 -13  32  14  23   8  20  15  27]
  [ 14  20   6  21   6  25   9  23  10  28   8  29   7  23]
  [ 10  29  12  25  12  27   9  26  11  24  13  30  15  30]]

 [[  7  32   6  31  12  28   6  20  14  32   7  28  15  24]
  [ 10  25   6  23  11  27  14  31   8  20  15  31   7  26]
  [  9  23   7  25  11  23   7  22   6  31   7  32  13  30]
  [  7  32  12  28  14  26   6  32  14  22   8  27  10  28]]

 [[  2  18   5  18   7  19   6  22   6  18   5   3  22   6]
  [  4  18   6  18   6  18   8  21   5  18   5   4  20   4]
  [  6  22   8  21   4  22   8  20   2  21   4   8  18   5]
  [  7  22   2  21   6  22   6  21   5  19   3   3  19   3]]

 [[ 10  20   7  22 -10  19   8  21   9  18   7  71  20  10]
  [ 10  18  10  22  11  19   9  20   9  18  11   9  20  10]
  [  8  18   8  18  10  19  10  20  11  18   8  12  18   9]
  [  9  20   7  21   8  18   8  19   9  20  12  12  18   7]]]
